version: '3'

services:
  backend:
    environment:
      - DJANGO_DEBUG=1
    command:
      [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"

  celery:
    command: celery -A backend worker -l info

  celery_beat:
    command: celery -A backend beat -l info
