version: '3'

services:

  db:
    image: postgres
    env_file:
      - env_private/db.env

  redis:
    image: redis:alpine

  backend:
    build: backend/.
    env_file:
      - env_private/web.env
      - env_private/db.env
    environment:
      - DJANGO_DEBUG=0
    volumes:
      - ./backend:/usr/src/todo/backend
    depends_on:
      - db
      - redis

  celery:
    build: backend/.
    env_file:
      - env_private/web.env
    command: celery -A backend worker --autoscale=10,0 -l info -E
    volumes:
      - ./backend:/usr/src/todo/backend
    depends_on:
      - backend

  celery_beat:
    build: backend/.
    env_file:
      - env_private/web.env
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/usr/src/todo/backend
    depends_on:
      - backend

  frontend:
    build: frontend/.
    volumes:
      - ./frontend/package.json:/usr/src/todo/package.json
      - ./frontend/package-lock.json:/usr/src/todo/package-lock.json
      - ./frontend:/usr/src/todo/frontend
    depends_on:
      - backend
