version: '3.8'

services:

  backend:
    ports:
      - 8000:8000
    user: root
    command:
      [ "gunicorn", "--bind", ":8000", "backend.wsgi:application" ]
    environment:
      - DJANGO_DEBUG=0
    volumes:
      - static_volume:/usr/src/todo/backend/static
      - media_volume:/usr/src/todo/backend/media

  frontend:
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    command:
      [ "npm", "run", "start" ]

  proxy:
    image: nginx:1.17
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - static_volume:/usr/src/todo/backend/static
      - media_volume:/usr/src/todo/backend/media
    ports:
      - 8765:80
    depends_on:
      - frontend

volumes:
  static_volume:
  media_volume:
