version: '3.8'

services:

  db:
    image: postgres
    env_file:
      - env_private/db.env
    networks:
      - db_layer

  redis:
    image: redis:alpine
    networks:
      - db_layer

  backend:
    build: backend/.
    env_file:
      - env_private/web.env
      - env_private/db.env
    environment:
      - DJANGO_DEBUG=0
    volumes:
      - ./backend:/usr/src/todo/backend
    depends_on:
      - db
      - redis
    networks:
      - db_layer

  celery:
    build: backend/.
    env_file:
      - env_private/web.env
    command: celery -A backend worker --autoscale=10,0 -l info
    volumes:
      - ./backend:/usr/src/todo/backend
    depends_on:
      - backend
    networks:
      - db_layer

  celery_beat:
    build: backend/.
    env_file:
      - env_private/web.env
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/usr/src/todo/backend
    depends_on:
      - backend
    networks:
      - db_layer

  frontend:
    build: frontend/.
    volumes:
      - ./frontend/package.json:/usr/src/todo/package.json
      - ./frontend/package-lock.json:/usr/src/todo/package-lock.json
      - ./frontend/nuxt.config.js:/usr/src/todo/nuxt.config.js
      - ./frontend/client:/usr/src/todo/client
    depends_on:
      - backend

networks:
  db_layer:
    driver: bridge
